Repo {repoSshUrl = "git@github.com:Glandos/fail2ban.git", repoDescription = Just "Daemon to ban hosts that cause multiple authentication errors", repoCreatedAt = GithubDate {fromGithubDate = 2013-03-24 11:16:05 UTC}, repoHtmlUrl = "https://github.com/Glandos/fail2ban", repoSvnUrl = "https://github.com/Glandos/fail2ban", repoForks = 0, repoHomepage = Just "http://www.fail2ban.org", repoFork = True, repoGitUrl = "git://github.com/Glandos/fail2ban.git", repoPrivate = False, repoCloneUrl = "https://github.com/Glandos/fail2ban.git", repoSize = 196, repoUpdatedAt = GithubDate {fromGithubDate = 2013-04-07 16:55:57 UTC}, repoWatchers = 0, repoOwner = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/f49f984a790556065284c1ac5b664c2b?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "Glandos", githubOwnerUrl = "https://api.github.com/users/Glandos", githubOwnerId = 297578, githubOwnerGravatarId = "f49f984a790556065284c1ac5b664c2b"}, repoName = "fail2ban", repoLanguage = Just "Python", repoMasterBranch = Just "master", repoPushedAt = Just (GithubDate {fromGithubDate = 2013-04-07 16:52:16 UTC}), repoId = 8984887, repoUrl = "https://api.github.com/repos/Glandos/fail2ban", repoOpenIssues = 0, repoHasWiki = Just False, repoHasIssues = Just False, repoHasDownloads = Just True}