IssueComment {issueCommentUpdatedAt = GithubDate {fromGithubDate = 2013-02-27 18:35:39 UTC}, issueCommentUser = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/1c8c366f3d722f54535930017e955aa1?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "kwirk", githubOwnerUrl = "https://api.github.com/users/kwirk", githubOwnerId = 328405, githubOwnerGravatarId = "1c8c366f3d722f54535930017e955aa1"}, issueCommentUrl = "https://api.github.com/repos/fail2ban/fail2ban/issues/comments/14190719", issueCommentCreatedAt = GithubDate {fromGithubDate = 2013-02-27 18:35:39 UTC}, issueCommentBody = "@yarikoptic I've added the ability to set log file encoding to the jail. Default is the system locale. If there any issues decoding a log line, it prints a warning to the fail2ban log. In python2 it maintains current behaviour of reverting back to `str`, but with pyhton3 it redoes the decode ignoring any errors (simply drops any parts of the line it cant decode).\r\n\r\nWasn't sure if python2 should suppress the warning message, as it just passes back to string; and also should python2 have the same behaviour of python3, requiring use of Unicode, ignoring any characters with decode errors?", issueCommentId = 14190719}