IssueComment {issueCommentUpdatedAt = GithubDate {fromGithubDate = 2013-03-30 22:08:25 UTC}, issueCommentUser = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/1c8c366f3d722f54535930017e955aa1?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "kwirk", githubOwnerUrl = "https://api.github.com/users/kwirk", githubOwnerId = 328405, githubOwnerGravatarId = "1c8c366f3d722f54535930017e955aa1"}, issueCommentUrl = "https://api.github.com/repos/fail2ban/fail2ban/issues/comments/15682802", issueCommentCreatedAt = GithubDate {fromGithubDate = 2013-03-30 22:08:25 UTC}, issueCommentBody = "_Travis CI_ config looks good now:\r\nhttps://travis-ci.org/kwirk/fail2ban/builds/5928256\r\n\r\nTurns out Travis CI doesn't support python 3.{0,1}, so I had to remove them.", issueCommentId = 15682802}