Repo {repoSshUrl = "git@github.com:blotus/fail2ban.git", repoDescription = Just "Daemon to ban hosts that cause multiple authentication errors", repoCreatedAt = GithubDate {fromGithubDate = 2013-01-25 12:34:10 UTC}, repoHtmlUrl = "https://github.com/blotus/fail2ban", repoSvnUrl = "https://github.com/blotus/fail2ban", repoForks = 0, repoHomepage = Just "http://www.fail2ban.org", repoFork = True, repoGitUrl = "git://github.com/blotus/fail2ban.git", repoPrivate = False, repoCloneUrl = "https://github.com/blotus/fail2ban.git", repoSize = 172, repoUpdatedAt = GithubDate {fromGithubDate = 2013-01-25 16:20:40 UTC}, repoWatchers = 0, repoOwner = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/b214c746227d26ef4b3cb275173a59f0?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "blotus", githubOwnerUrl = "https://api.github.com/users/blotus", githubOwnerId = 835060, githubOwnerGravatarId = "b214c746227d26ef4b3cb275173a59f0"}, repoName = "fail2ban", repoLanguage = Just "Python", repoMasterBranch = Just "master", repoPushedAt = Just (GithubDate {fromGithubDate = 2013-01-25 12:37:24 UTC}), repoId = 7819838, repoUrl = "https://api.github.com/repos/blotus/fail2ban", repoOpenIssues = 0, repoHasWiki = Just False, repoHasIssues = Just False, repoHasDownloads = Just True}