Repo {repoSshUrl = "git@github.com:gebi/fail2ban.git", repoDescription = Just "Daemon to ban hosts that cause multiple authentication errors", repoCreatedAt = GithubDate {fromGithubDate = 2013-01-03 17:47:55 UTC}, repoHtmlUrl = "https://github.com/gebi/fail2ban", repoSvnUrl = "https://github.com/gebi/fail2ban", repoForks = 0, repoHomepage = Just "http://www.fail2ban.org", repoFork = True, repoGitUrl = "git://github.com/gebi/fail2ban.git", repoPrivate = False, repoCloneUrl = "https://github.com/gebi/fail2ban.git", repoSize = 160, repoUpdatedAt = GithubDate {fromGithubDate = 2013-01-25 16:32:58 UTC}, repoWatchers = 0, repoOwner = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/64f81c5ea93797e96bd1f7f694fccea9?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "gebi", githubOwnerUrl = "https://api.github.com/users/gebi", githubOwnerId = 659, githubOwnerGravatarId = "64f81c5ea93797e96bd1f7f694fccea9"}, repoName = "fail2ban", repoLanguage = Just "Python", repoMasterBranch = Just "master", repoPushedAt = Just (GithubDate {fromGithubDate = 2013-01-04 15:09:27 UTC}), repoId = 7427302, repoUrl = "https://api.github.com/repos/gebi/fail2ban", repoOpenIssues = 0, repoHasWiki = Just False, repoHasIssues = Just False, repoHasDownloads = Just True}