IssueComment {issueCommentUpdatedAt = GithubDate {fromGithubDate = 2013-04-10 16:13:04 UTC}, issueCommentUser = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/78225da31896e34ca3196c46fae08bf4?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "Th4nat0s", githubOwnerUrl = "https://api.github.com/users/Th4nat0s", githubOwnerId = 1728186, githubOwnerGravatarId = "78225da31896e34ca3196c46fae08bf4"}, issueCommentUrl = "https://api.github.com/repos/fail2ban/fail2ban/issues/comments/16184434", issueCommentCreatedAt = GithubDate {fromGithubDate = 2013-04-10 16:13:04 UTC}, issueCommentBody = "Yes it's your localhost!! \r\n\r\nRealRancor <notifications@github.com> wrote:\r\n\r\n>Hi,\r\n>\r\n>when using the patch from Th4nat0s i'm getting this warning in my\r\n>fail2ban.log:\r\n>\r\n>2013-04-10 17:55:33,165 fail2ban.filter : WARNING Unable to find a\r\n>corresponding IP address for ::1:\r\n>\r\n>Is this something i have to worry?\r\n>\r\n>---\r\n>Reply to this email directly or view it on GitHub:\r\n>https://github.com/fail2ban/fail2ban/pull/88#issuecomment-16184275\r\n\r\n-- \r\nSent from my Android phone with K-9 Mail. Please excuse my brevity.", issueCommentId = 16184434}