IssueComment {issueCommentUpdatedAt = GithubDate {fromGithubDate = 2013-04-10 16:13:56 UTC}, issueCommentUser = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/f6105e79dfcfb0fcbabb3db061135c08?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "RealRancor", githubOwnerUrl = "https://api.github.com/users/RealRancor", githubOwnerId = 2248459, githubOwnerGravatarId = "f6105e79dfcfb0fcbabb3db061135c08"}, issueCommentUrl = "https://api.github.com/repos/fail2ban/fail2ban/issues/comments/16184275", issueCommentCreatedAt = GithubDate {fromGithubDate = 2013-04-10 16:10:24 UTC}, issueCommentBody = "Hi,\r\n\r\nwhen using the patch from Th4nat0s i'm getting this warning in my fail2ban.log:\r\n\r\n    2013-04-10 17:55:33,165 fail2ban.filter : WARNING Unable to find a corresponding IP address for ::1:\r\n\r\nIs this something i have to worry? In the meantime i will test the branch from yarikoptic", issueCommentId = 16184275}