Repo {repoSshUrl = "git@github.com:arto-p/fail2ban.git", repoDescription = Just "Daemon to ban hosts that cause multiple authentication errors", repoCreatedAt = GithubDate {fromGithubDate = 2013-03-22 10:29:56 UTC}, repoHtmlUrl = "https://github.com/arto-p/fail2ban", repoSvnUrl = "https://github.com/arto-p/fail2ban", repoForks = 0, repoHomepage = Just "http://www.fail2ban.org", repoFork = True, repoGitUrl = "git://github.com/arto-p/fail2ban.git", repoPrivate = False, repoCloneUrl = "https://github.com/arto-p/fail2ban.git", repoSize = 176, repoUpdatedAt = GithubDate {fromGithubDate = 2013-04-09 22:49:14 UTC}, repoWatchers = 0, repoOwner = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/2202581ddde11ceefc92b7e85068a5f1?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "arto-p", githubOwnerUrl = "https://api.github.com/users/arto-p", githubOwnerId = 3940184, githubOwnerGravatarId = "2202581ddde11ceefc92b7e85068a5f1"}, repoName = "fail2ban", repoLanguage = Just "Python", repoMasterBranch = Just "master", repoPushedAt = Just (GithubDate {fromGithubDate = 2013-03-25 14:07:04 UTC}), repoId = 8949674, repoUrl = "https://api.github.com/repos/arto-p/fail2ban", repoOpenIssues = 0, repoHasWiki = Just False, repoHasIssues = Just False, repoHasDownloads = Just True}