IssueComment {issueCommentUpdatedAt = GithubDate {fromGithubDate = 2013-01-17 18:27:20 UTC}, issueCommentUser = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/1c8c366f3d722f54535930017e955aa1?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "kwirk", githubOwnerUrl = "https://api.github.com/users/kwirk", githubOwnerId = 328405, githubOwnerGravatarId = "1c8c366f3d722f54535930017e955aa1"}, issueCommentUrl = "https://api.github.com/repos/fail2ban/fail2ban/issues/comments/12381555", issueCommentCreatedAt = GithubDate {fromGithubDate = 2013-01-17 18:27:20 UTC}, issueCommentBody = "@bluephoenix47 Thanks for testing.\r\n\r\nCould you confirm what version of `python` and `systemd` is install.\r\n\r\nCould you also try setting the `loglevel = 4` in `fail2ban.conf`", issueCommentId = 12381555}