IssueComment {issueCommentUpdatedAt = GithubDate {fromGithubDate = 2013-01-25 21:43:15 UTC}, issueCommentUser = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/3234c2bb3f7334073304577dbe2244f5?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "pedrosland", githubOwnerUrl = "https://api.github.com/users/pedrosland", githubOwnerId = 119412, githubOwnerGravatarId = "3234c2bb3f7334073304577dbe2244f5"}, issueCommentUrl = "https://api.github.com/repos/fail2ban/fail2ban/issues/comments/12722280", issueCommentCreatedAt = GithubDate {fromGithubDate = 2013-01-25 21:43:15 UTC}, issueCommentBody = "For comparison here are [my results](http://sprunge.us/CEIZ). I don't have pyinotify so I don't expect that one to pass. I also know that gamin hasn't worked for ages. I haven't looked into why - if it is fail2ban or Arch that has the problem.", issueCommentId = 12722280}