IssueComment {issueCommentUpdatedAt = GithubDate {fromGithubDate = 2013-01-29 18:24:56 UTC}, issueCommentUser = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/1c8c366f3d722f54535930017e955aa1?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "kwirk", githubOwnerUrl = "https://api.github.com/users/kwirk", githubOwnerId = 328405, githubOwnerGravatarId = "1c8c366f3d722f54535930017e955aa1"}, issueCommentUrl = "https://api.github.com/repos/fail2ban/fail2ban/issues/comments/12849449", issueCommentCreatedAt = GithubDate {fromGithubDate = 2013-01-29 18:24:56 UTC}, issueCommentBody = "@bluephoenix47 It's not apparent what the issues are from the outputs you posted. Might be worth testing with the recent `fail2ban-regex` changes I've made to check if the regex is matching okay:\r\n\r\n    python2 fail2ban-regex -m \"SYSLOG_IDENTIFIER=fail2ban-testcases\" systemd-journal '(?:(?:Authentication failure|Failed [-/\\w+]+) for(?: [iI](?:llegal|nvalid) user)?|[Ii](?:llegal|nvalid) user|ROOT LOGIN REFUSED) .*(?: from|FROM) <HOST>'\r\n", issueCommentId = 12849449}