IssueComment {issueCommentUpdatedAt = GithubDate {fromGithubDate = 2012-08-14 20:21:09 UTC}, issueCommentUser = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/6a424256589825f609fd3477144355a0?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "yarikoptic", githubOwnerUrl = "https://api.github.com/users/yarikoptic", githubOwnerId = 39889, githubOwnerGravatarId = "6a424256589825f609fd3477144355a0"}, issueCommentUrl = "https://api.github.com/repos/fail2ban/fail2ban/issues/comments/7738850", issueCommentCreatedAt = GithubDate {fromGithubDate = 2012-08-14 20:21:09 UTC}, issueCommentBody = "IIRC no action should be invoked on an already banned IP  in the same jail -- please provide further details (e.g. relevant parts of fail2ban.log showing ban, and then subsequent second invocation of banaction which sends email).", issueCommentId = 7738850}