IssueComment {issueCommentUpdatedAt = GithubDate {fromGithubDate = 2012-08-17 15:07:44 UTC}, issueCommentUser = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/e782561a98d0e131cbd4980f62853597?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "mikeg-de", githubOwnerUrl = "https://api.github.com/users/mikeg-de", githubOwnerId = 604842, githubOwnerGravatarId = "e782561a98d0e131cbd4980f62853597"}, issueCommentUrl = "https://api.github.com/repos/fail2ban/fail2ban/issues/comments/7825463", issueCommentCreatedAt = GithubDate {fromGithubDate = 2012-08-17 15:07:44 UTC}, issueCommentBody = "The sshd were all merged in the messages file. I'm tried to separate this by adding the following filter to /etc/syslog-ng/syslog-ng.conf:\n# SSH Filters\nfilter f_sshderr    { match('^sshd\\[[0-9]+\\]: error:'); };\nfilter f_sshd       { match('^sshd\\[[0-9]+\\]:'); };\n\n# SSH Logging\ndestination sshderr { file(\"/var/log/sshd/sshderr.log\"); };\nlog { source(src); filter(f_sshderr); destination(sshderr); flags(final); };\n\ndestination sshd { file(\"/var/log/sshd/sshd.log\"); };\nlog { source(src); filter(f_sshd); destination(sshd); flags(final); };\n\nAfter restarting syslog service nothing changed. I think that might be the source of the issue since both actions check the same log file. What do you think?", issueCommentId = 7825463}