Issue {issueClosedAt = Nothing, issueUpdatedAt = GithubDate {fromGithubDate = 2012-12-29 14:19:12 UTC}, issueHtmlUrl = "https://github.com/fail2ban/fail2ban/issues/101", issueClosedBy = Nothing, issueLabels = [], issueNumber = 101, issueAssignee = Nothing, issueUser = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/8427e70679b4221b8582cb8beeca0f65?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "hamilton5", githubOwnerUrl = "https://api.github.com/users/hamilton5", githubOwnerId = 2685451, githubOwnerGravatarId = "8427e70679b4221b8582cb8beeca0f65"}, issueTitle = "iptables-allports and port", issuePullRequest = PullRequestReference {pullRequestReferenceHtmlUrl = Nothing, pullRequestReferencePatchUrl = Nothing, pullRequestReferenceDiffUrl = Nothing}, issueUrl = "https://api.github.com/repos/fail2ban/fail2ban/issues/101", issueCreatedAt = GithubDate {fromGithubDate = 2012-12-29 14:12:08 UTC}, issueBody = "'port =  ' still needs to be specified under the section even tho banaction is iptables-allports\r\n\r\nRestarting fail2ban monitor: fail2banTraceback (most recent call last):\r\n  File \"/usr/bin/fail2ban-client\", line 401, in <module>\r\n    if client.start(sys.argv):\r\n  File \"/usr/bin/fail2ban-client\", line 370, in start\r\n    return self.__processCommand(args)\r\n  File \"/usr/bin/fail2ban-client\", line 180, in __processCommand\r\n    ret = self.__readConfig()\r\n  File \"/usr/bin/fail2ban-client\", line 375, in __readConfig\r\n    ret = self.__configurator.getOptions()\r\n  File \"/usr/share/fail2ban/client/configurator.py\", line 65, in getOptions\r\n    return self.__jails.getOptions(jail)\r\n  File \"/usr/share/fail2ban/client/jailsreader.py\", line 64, in getOptions\r\n    ret = jail.getOptions()\r\n  File \"/usr/share/fail2ban/client/jailreader.py\", line 70, in getOptions\r\n    self.__opts = ConfigReader.getOptions(self, self.__name, opts)\r\n  File \"/usr/share/fail2ban/client/configreader.py\", line 84, in getOptions\r\n    v = self.get(sec, option[1])\r\n  File \"/usr/lib/python2.6/ConfigParser.py\", line 546, in get\r\n    return self._interpolate(section, option, value, d)\r\n  File \"/usr/lib/python2.6/ConfigParser.py\", line 614, in _interpolate\r\n    self._interpolate_some(option, L, rawval, section, vars, 1)\r\n  File \"/usr/lib/python2.6/ConfigParser.py\", line 649, in _interpolate_some\r\n    section, map, depth + 1)\r\n  File \"/usr/lib/python2.6/ConfigParser.py\", line 646, in _interpolate_some\r\n    option, section, rest, var)\r\nConfigParser.InterpolationMissingOptionError: Bad value substitution:\r\n        section: [mysection]\r\n        option : action\r\n        key    : port\r\n        rawval : \", protocol=\"%(protocol)s]\r\n%(mta)s-whois[name=%(__name__)s, dest=\"%(destemail)s\", protocol=\"%(protocol)s]\r\n", issueState = "open", issueId = 9573654, issueComments = 0, issueMilestone = Nothing}