Issue {issueClosedAt = Nothing, issueUpdatedAt = GithubDate {fromGithubDate = 2013-02-27 18:35:39 UTC}, issueHtmlUrl = "https://github.com/fail2ban/fail2ban/issues/128", issueClosedBy = Nothing, issueLabels = [], issueNumber = 128, issueAssignee = Nothing, issueUser = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/1c8c366f3d722f54535930017e955aa1?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "kwirk", githubOwnerUrl = "https://api.github.com/users/kwirk", githubOwnerId = 328405, githubOwnerGravatarId = "1c8c366f3d722f54535930017e955aa1"}, issueTitle = "Python3 support", issuePullRequest = PullRequestReference {pullRequestReferenceHtmlUrl = Just "https://github.com/fail2ban/fail2ban/pull/128", pullRequestReferencePatchUrl = Just "https://github.com/fail2ban/fail2ban/pull/128.patch", pullRequestReferenceDiffUrl = Just "https://github.com/fail2ban/fail2ban/pull/128.diff"}, issueUrl = "https://api.github.com/repos/fail2ban/fail2ban/issues/128", issueCreatedAt = GithubDate {fromGithubDate = 2013-02-24 18:56:31 UTC}, issueBody = "I've made some changes that enable fail2ban to work with python3 once _2to3_ has been used. Fail2ban still functions with python2.4+ (if you haven't run _2to3_ of course :wink:)\r\n\r\nOne potential issue, is that all log files are opened as 'utf-8' encoding, with encoding errors ignored. Not sure how much of an issue this is, as far is I'm aware, all logs are utf-8 or plain ascii.\r\nDid consider logging a warning if failed to decode a log line, but was worried would spam the fail2ban log files if there is a reoccurring issue.\r\nAlso looked at just using bytes, but then regexs complain, such that you need both a compiled _bytes_ and _str/unicode_ for regexs.\r\n\r\nI've run testscases on python2.[4-7] and python3.[0-3] with success. Also ran actively with python2.7 and python3.3 and all seems to function with no issues.\r\n\r\nTo use, execute `./fail2ban-2to3`. You can then use `./fail2ban-testcases-all-python3` or `./fail2ban-testcases` to run tests.\r\n\r\nAny testers would be appreciated. :smile:\r\n\r\nThanks\r\n", issueState = "open", issueId = 11338217, issueComments = 4, issueMilestone = Nothing}