Issue {issueClosedAt = Nothing, issueUpdatedAt = GithubDate {fromGithubDate = 2013-03-11 01:44:07 UTC}, issueHtmlUrl = "https://github.com/fail2ban/fail2ban/issues/130", issueClosedBy = Nothing, issueLabels = [], issueNumber = 130, issueAssignee = Nothing, issueUser = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/e0bcd9413a02172cdb0c1c711bf7068b?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "sebres", githubOwnerUrl = "https://api.github.com/users/sebres", githubOwnerId = 3769657, githubOwnerGravatarId = "e0bcd9413a02172cdb0c1c711bf7068b"}, issueTitle = "bug fix: invalid date recognition, irregular because of sorting template list...", issuePullRequest = PullRequestReference {pullRequestReferenceHtmlUrl = Just "https://github.com/fail2ban/fail2ban/pull/130", pullRequestReferencePatchUrl = Just "https://github.com/fail2ban/fail2ban/pull/130.patch", pullRequestReferenceDiffUrl = Just "https://github.com/fail2ban/fail2ban/pull/130.diff"}, issueUrl = "https://api.github.com/repos/fail2ban/fail2ban/issues/130", issueCreatedAt = GithubDate {fromGithubDate = 2013-03-04 23:08:27 UTC}, issueBody = "... (sometimes not reproducible by fail2ban-regex, cause will be not sorted)\r\n\r\ndate in following log line (from nginx) will be wrong detected:\r\n2012/10/11 02:37:17 [error] 18434#0: *947 user \"test\" was not found in \"/www/...\", client: 192.168.1.5, ...\r\n\r\nsometimes it is [correct] - 2012/10/11 (%Y/%m/%d) = 1349919861.71\r\nsometimes it is [invalid] -   12/10/11 (%d/%m/%y) = 1349915838.06\r\nand older as now - 1800 seconds (therefore will be not found)\r\n\r\nsolution: regular expression fixed, cause date in log used always after non symbol (\\W) character, so r\"\\d{2}/\\d{2}/\\d{2}\" will be r\"(?<!\\w)\\d{2}/\\d{2}/\\d{2}\".", issueState = "open", issueId = 11644063, issueComments = 1, issueMilestone = Nothing}