Issue {issueClosedAt = Nothing, issueUpdatedAt = GithubDate {fromGithubDate = 2013-03-27 18:46:48 UTC}, issueHtmlUrl = "https://github.com/fail2ban/fail2ban/issues/145", issueClosedBy = Nothing, issueLabels = [], issueNumber = 145, issueAssignee = Nothing, issueUser = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/53f4f76d6b82fc8a39b30375fa8fca4d?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "theskystalker", githubOwnerUrl = "https://api.github.com/users/theskystalker", githubOwnerId = 3897395, githubOwnerGravatarId = "53f4f76d6b82fc8a39b30375fa8fca4d"}, issueTitle = "Update lighttpd-auth filter", issuePullRequest = PullRequestReference {pullRequestReferenceHtmlUrl = Just "https://github.com/fail2ban/fail2ban/pull/145", pullRequestReferencePatchUrl = Just "https://github.com/fail2ban/fail2ban/pull/145.patch", pullRequestReferenceDiffUrl = Just "https://github.com/fail2ban/fail2ban/pull/145.diff"}, issueUrl = "https://api.github.com/repos/fail2ban/fail2ban/issues/145", issueCreatedAt = GithubDate {fromGithubDate = 2013-03-18 10:24:24 UTC}, issueBody = "Added 3rd expression variant (\"get_password failed\")\r\nComes when trying to login with a not existing Username.\r\nTested on my System, works fine.\r\n\r\nSystem:\r\nLinux version 2.6.32-5-amd64 (Debian 2.6.32-48squeeze1) (dannf@debian.org) (gcc version 4.3.5 (Debian 4.3.5-4) ) #1 SMP Mon Feb 25 00:26:11 UTC 2013\r\nlighttpd/1.4.28 (ssl) (Mar 15 2013 19:01:10) - a light and fast webserver\r\n\r\nbr\r\nSkystalker\r\n", issueState = "open", issueId = 12127412, issueComments = 4, issueMilestone = Nothing}