Issue {issueClosedAt = Nothing, issueUpdatedAt = GithubDate {fromGithubDate = 2013-01-25 16:16:50 UTC}, issueHtmlUrl = "https://github.com/fail2ban/fail2ban/issues/63", issueClosedBy = Nothing, issueLabels = [], issueNumber = 63, issueAssignee = Nothing, issueUser = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/b36b7de57d8f5d07b5c74ed29afd8a6a?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "mlangelaar", githubOwnerUrl = "https://api.github.com/users/mlangelaar", githubOwnerId = 283440, githubOwnerGravatarId = "b36b7de57d8f5d07b5c74ed29afd8a6a"}, issueTitle = "No warning if *logpath* improperly configured or file missing", issuePullRequest = PullRequestReference {pullRequestReferenceHtmlUrl = Nothing, pullRequestReferencePatchUrl = Nothing, pullRequestReferenceDiffUrl = Nothing}, issueUrl = "https://api.github.com/repos/fail2ban/fail2ban/issues/63", issueCreatedAt = GithubDate {fromGithubDate = 2012-07-13 15:36:36 UTC}, issueBody = "This can save new users hours of frustration. Not a serious error at all,\njust something that might save people hours of looking around :)\n\nAfter spending hours trying to figure out why my fail2ban was not banning, I\nthought to myself, why not run verbose mode, and maybe some extra info\nmight appear (the following run from the command line) :\n\n    fail2ban-client -v start\n\nDoing so revealed the following error ERROR :\n\n# fail2ban-client start\nWARNING 'action' not defined in 'php-url-fopen'. Using default value\nWARNING 'action' not defined in 'lighttpd-fastcgi'. Using default value\nERROR  No file found for /var/log/mail.log\n2012-07-13 10:10:57,284 fail2ban.server : INFO   Starting Fail2ban v0.8.5\n2012-07-13 10:10:57,287 fail2ban.server : INFO   Starting in daemon mode\n\nPost Note : turns out you don't need verbose (-v) to get the above info.\n\nThis ERROR does not appear if you use the *normal* way of starting fail2ban :\n\n   /etc/init.d/fail2ban start\n\nUnfortunately the ERROR is not written to log or anywhere else I can see.\n\nI only found it after running the fail2ban client on the command line.\n\nMaiko Langelaar\nIT Physics and Astronomy\nUniversity of Manitoba\n", issueState = "open", issueId = 5605411, issueComments = 0, issueMilestone = Just (Milestone {milestoneCreator = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/6a424256589825f609fd3477144355a0?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "yarikoptic", githubOwnerUrl = "https://api.github.com/users/yarikoptic", githubOwnerId = 39889, githubOwnerGravatarId = "6a424256589825f609fd3477144355a0"}, milestoneDueOn = Nothing, milestoneOpenIssues = 2, milestoneNumber = 4, milestoneClosedIssues = 6, milestoneDescription = "Bugfix release in 0.8 series", milestoneTitle = "0.8.9", milestoneUrl = "https://api.github.com/repos/fail2ban/fail2ban/milestones/4", milestoneCreatedAt = GithubDate {fromGithubDate = 2013-01-25 16:14:20 UTC}, milestoneState = "open"})}